# Generated by Django 5.0.1 on 2024-01-10 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roleplay_manager", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PasswordResetRequest",
            new_name="TokenRequest",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="full_name",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="password",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
