# Generated by Django 5.0.1 on 2024-01-12 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roleplay_manager", "0002_rename_passwordresetrequest_tokenrequest_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="characterinfo",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="feedback",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="modelinfo",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RemoveField(
            model_name="characterinfo",
            name="display_prompt",
        ),
        migrations.RemoveField(
            model_name="characterinfo",
            name="tag_id",
        ),
        migrations.RemoveField(
            model_name="modelinfo",
            name="accessibility",
        ),
        migrations.RemoveField(
            model_name="modelinfo",
            name="used_for",
        ),
        migrations.AddField(
            model_name="characterinfo",
            name="model_id",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="character_model",
                to="roleplay_manager.modelinfo",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="characterinfo",
            name="prompt_visibility",
            field=models.CharField(
                choices=[
                    ("private", "Private"),
                    ("unlisted", "Unlisted"),
                    ("public", "Public"),
                ],
                default="unlisted",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="characterinfo",
            name="tags",
            field=models.CharField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="modelinfo",
            name="short_bio",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="characterinfo",
            name="character_gender",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="characterinfo",
            name="image",
            field=models.ImageField(upload_to=""),
        ),
        migrations.AlterField(
            model_name="characterinfo",
            name="initial_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="characterinfo",
            name="lorebook",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="receiver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receiver_user",
                to="roleplay_manager.characterinfo",
            ),
        ),
        migrations.AlterField(
            model_name="modelinfo",
            name="prompt_template",
            field=models.TextField(default=""),
        ),
    ]
