# Generated by Django 5.0.1 on 2024-01-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roleplay_manager", "0003_rename_user_id_characterinfo_user_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tag",
            old_name="user_added_by",
            new_name="user",
        ),
        migrations.AlterField(
            model_name="characterinfo",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
