# Generated by Django 5.0.1 on 2024-01-19 05:13

import django.db.models.deletion
import shortuuidfield.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roleplay_manager", "0004_rename_user_added_by_tag_user_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="characterinfo",
            old_name="prompt_visibility",
            new_name="character_visibility",
        ),
        migrations.RenameField(
            model_name="chatmessage",
            old_name="message",
            new_name="character_message",
        ),
        migrations.RemoveField(
            model_name="chatmessage",
            name="group_id",
        ),
        migrations.RemoveField(
            model_name="chatmessage",
            name="receiver",
        ),
        migrations.RemoveField(
            model_name="chatmessage",
            name="room_group_name",
        ),
        migrations.RemoveField(
            model_name="chatmessage",
            name="sender",
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="user_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="ChatRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True, null=True)),
                ("modified_date", models.DateTimeField(auto_now=True, null=True)),
                (
                    "room_id",
                    shortuuidfield.fields.ShortUUIDField(
                        blank=True, editable=False, max_length=22
                    ),
                ),
                (
                    "type",
                    models.PositiveIntegerField(
                        choices=[(1, "DM"), (2, "Group")], default=1
                    ),
                ),
                ("group_name", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "character",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="character",
                        to="roleplay_manager.characterinfo",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sender",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="chat",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chatroom",
                to="roleplay_manager.chatroom",
            ),
        ),
    ]
