# Generated by Django 5.0.1 on 2024-01-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "roleplay_manager",
            "0005_rename_prompt_visibility_characterinfo_character_visibility_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="characterinfo",
            name="tags",
            field=models.CharField(max_length=100),
        ),
    ]
