# Generated by Django 5.0.1 on 2024-01-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roleplay_manager", "0006_alter_characterinfo_tags"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tag",
            old_name="tag_id",
            new_name="id",
        ),
        migrations.RemoveField(
            model_name="characterinfo",
            name="tags",
        ),
        migrations.AddField(
            model_name="characterinfo",
            name="tags",
            field=models.ManyToManyField(
                related_name="character_tag", to="roleplay_manager.tag"
            ),
        ),
    ]
