# Generated by Django 5.0.1 on 2024-01-31 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "roleplay_manager",
            "0007_rename_tag_id_tag_id_remove_characterinfo_tags_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="feedback",
            old_name="review",
            new_name="content",
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="rating",
        ),
        migrations.AddField(
            model_name="feedback",
            name="types",
            field=models.CharField(default=""),
            preserve_default=False,
        ),
    ]
