# Generated by Django 5.0.1 on 2024-02-02 09:23

from django.db import migrations, models
import random

def set_unique_values(apps, schema_editor):
    CustomUser = apps.get_model('roleplay_manager', 'CustomUser')

    # Add logic to set unique values for the existing data
    for user in CustomUser.objects.all():
        if not user.full_name:
            user.full_name = f"{user.email.split('@')[0]}"
        user.username = f"{user.email.split('@')[0]}{random.randint(0000000, 9999999)}"
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        ("roleplay_manager", "0009_alter_characterinfo_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="username",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.RunPython(set_unique_values),
    ]
