# Generated by Django 5.0.1 on 2024-02-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roleplay_manager", "0010_customuser_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="types",
            field=models.CharField(max_length=255),
        ),
    ]
