# Generated by Django 5.0.1 on 2024-02-14 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "roleplay_manager",
            "0013_alter_characterinfo_user_alter_chatmessage_chat_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="characterinfo",
            name="character_story",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Lorebook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True, null=True)),
                ("modified_date", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_public", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lorebook_infos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LorebookEntries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True, null=True)),
                ("modified_date", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=200)),
                ("keys", models.TextField(blank=True, null=True)),
                ("condition", models.CharField(max_length=20)),
                ("secondary_keys", models.TextField(blank=True, null=True)),
                ("content", models.TextField(blank=True, null=True)),
                ("probability", models.IntegerField(default=100)),
                ("order", models.IntegerField(default=100)),
                ("is_enabled", models.BooleanField(default=True)),
                ("is_exclude_recursion", models.BooleanField(default=False)),
                (
                    "lorebook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lorebook_entry_infos",
                        to="roleplay_manager.lorebook",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
