# Generated by Django 5.0.1 on 2024-02-14 15:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roleplay_manager", "0014_characterinfo_character_story_lorebook_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="modelinfo",
            name="prompt_template",
        ),
        migrations.RemoveField(
            model_name="modelinfo",
            name="repetition_penalty",
        ),
        migrations.RemoveField(
            model_name="modelinfo",
            name="temperature",
        ),
        migrations.RemoveField(
            model_name="modelinfo",
            name="top_k",
        ),
        migrations.RemoveField(
            model_name="modelinfo",
            name="top_p",
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_developer",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="UserCustomModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True, null=True)),
                ("modified_date", models.DateTimeField(auto_now=True, null=True)),
                ("is_default", models.BooleanField(default=True)),
                ("prompt_template", models.TextField(default="")),
                (
                    "temperature",
                    models.FloatField(
                        default=0.85,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(2),
                        ],
                    ),
                ),
                (
                    "repetition_penalty",
                    models.FloatField(
                        default=1.15,
                        validators=[
                            django.core.validators.MinValueValidator(0.01),
                            django.core.validators.MaxValueValidator(2),
                        ],
                    ),
                ),
                (
                    "top_p",
                    models.FloatField(
                        default=0.8,
                        validators=[
                            django.core.validators.MinValueValidator(0.01),
                            django.core.validators.MaxValueValidator(0.99),
                        ],
                    ),
                ),
                (
                    "top_k",
                    models.IntegerField(
                        default=50,
                        validators=[
                            django.core.validators.MinValueValidator(-1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "custom_model_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_model_info",
                        to="roleplay_manager.modelinfo",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_user_modal",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
