# Generated by Django 5.0.1 on 2024-02-20 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roleplay_manager', '0016_remove_customuser_is_developer_modelinfo_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_guest',
            field=models.BooleanField(default=False),
        ),
    ]
