# Generated by Django 5.0.1 on 2024-02-23 14:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roleplay_manager', '0017_customuser_is_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelinfo',
            name='huggingFace_model_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='modelinfo',
            name='is_finetune',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modelinfo',
            name='prompt_template',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='modelinfo',
            name='repetition_penalty',
            field=models.FloatField(default=1.15, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AddField(
            model_name='modelinfo',
            name='temperature',
            field=models.FloatField(default=0.85, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AddField(
            model_name='modelinfo',
            name='top_k',
            field=models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='modelinfo',
            name='top_p',
            field=models.FloatField(default=0.8, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(0.99)]),
        ),
        migrations.AlterField(
            model_name='modelinfo',
            name='model_location',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='modelinfo',
            name='model_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='LoraModelInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('lora_model_name', models.CharField(max_length=100)),
                ('lora_short_bio', models.TextField()),
                ('dataset', models.TextField(max_length=100)),
                ('tuned_model_path', models.CharField(default='', max_length=255)),
                ('num_train_epochs', models.PositiveIntegerField(default=1)),
                ('per_device_train_batch_size', models.PositiveIntegerField(default=1)),
                ('learning_rate', models.FloatField(default=0.0002)),
                ('warmup_steps', models.PositiveIntegerField(default=0)),
                ('optimizer', models.CharField(choices=[('adamw_hf', 'adamw_hf'), ('adamw_torch', 'adamw_torch'), ('adamw_torch_fused', 'adamw_torch_fused'), ('adamw_torch_xla', 'adamw_torch_xla'), ('adamw_torch_npu_fused', 'adamw_torch_npu_fused'), ('adamw_apex_fused', 'adamw_apex_fused'), ('adafactor', 'adafactor'), ('adamw_anyprecision', 'adamw_anyprecision'), ('sgd', 'sgd'), ('adagrad', 'adagrad'), ('adamw_bnb_8bit', 'adamw_bnb_8bit'), ('adamw_8bit', 'adamw_8bit'), ('lion_8bit', 'lion_8bit'), ('lion_32bit', 'lion_32bit'), ('paged_adamw_32bit', 'paged_adamw_32bit'), ('paged_adamw_8bit', 'paged_adamw_8bit'), ('paged_lion_32bit', 'paged_lion_32bit'), ('paged_lion_8bit', 'paged_lion_8bit'), ('rmsprop', 'rmsprop')], default='paged_adamw_8bit', max_length=100)),
                ('lr_scheduler_type', models.CharField(choices=[('constant', 'constant'), ('linear', 'linear'), ('cosine', 'cosine'), ('cosine_with_restarts', 'cosine_with_restarts'), ('polynomial', 'polynomial'), ('constant_with_warmup', 'constant_with_warmup'), ('inverse_sqrt', 'inverse_sqrt'), ('reduce_lr_on_plateau', 'reduce_lr_on_plateau')], default='constant', max_length=100)),
                ('gradient_accumulation_steps', models.PositiveIntegerField(default=1)),
                ('lora_alpha', models.PositiveIntegerField(default=32)),
                ('lora_dropout', models.FloatField(default=0.05)),
                ('lora_r', models.PositiveIntegerField(default=8)),
                ('lora_bias', models.CharField(choices=[('none', 'none'), ('all', 'all'), ('lora_only', 'lora only')], default='lora_only', max_length=100)),
                ('base_model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Base_model_info', to='roleplay_manager.modelinfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lora_modal_creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='UserCustomModel',
        ),
    ]
