# Generated by Django 5.0.1 on 2024-02-27 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roleplay_manager', '0018_modelinfo_huggingface_model_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loramodelinfo',
            name='lora_bias',
            field=models.CharField(choices=[('none', 'none'), ('all', 'all'), ('lora_only', 'lora only')], default='none', max_length=100),
        ),
        migrations.CreateModel(
            name='LoraTrainingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('current_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('error', 'Error')], max_length=20, null=True)),
                ('lora_training_error', models.TextField(blank=True, default='', null=True)),
                ('lora_model_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lora_model_info', to='roleplay_manager.loramodelinfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lora_modal_training', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
