# Generated by Django 5.0.1 on 2024-03-04 11:23

import django.db.models.deletion
import shortuuidfield.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roleplay_manager', '0020_alter_loramodelinfo_dataset_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdapterChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('adapter_room_id', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22)),
                ('type', models.PositiveIntegerField(choices=[(1, 'DM'), (2, 'Group')], default=1)),
                ('group_name', models.CharField(blank=True, max_length=30, null=True)),
                ('adapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Lora_adapter', to='roleplay_manager.loramodelinfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Adapter_sender', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdapterChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('user_message', models.TextField(blank=True, null=True)),
                ('adapter_message', models.TextField(blank=True, null=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('adapter_chatroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adapterChatRoom', to='roleplay_manager.adapterchatroom')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
