# Generated by Django 5.0.1 on 2024-03-07 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roleplay_manager', '0021_adapterchatroom_adapterchatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterinfo',
            name='character_story',
            field=models.TextField(blank=True, null=True),
        ),
    ]
